version: '3.4'
services:
    yansongda:
        image: registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:hyperf-8.1
        container_name: yansongda
        restart: always
        networks:
            - yansongda
        ports:
            - "8080:8080"
        volumes:
            - ./:/www

networks:
    yansongda:
