version: '3.8'
services:
    easycti:
        image: registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:hyperf-8.3
        container_name: yansongda
        restart: always
        networks:
            - yansongda
        ports:
            - "8080:8080"
        volumes:
            - ./:/www
        cap_add:
            - SYS_PTRACE
        sysctls:
            - net.unix.max_dgram_qlen=10

networks:
    yansongda:
